name: Merge branch with labeled
on:
  pull_request:
    types: [labeled]
jobs:
  merge-branch:
    if: ${{ github.event.label.name == 'merge' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Rebase
        run: git rebase ${{ github.head_ref || github.ref_name }}

      - name: Push
        run: git push
